### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by ghost** [m0n0l0c0/gitbook-plugin-index-of-figures#1]
# Description
`gitbook serve` crashes every time using this plugin.

# Log
```
TypeError: Cannot read property 'replace' of undefined
    at Node.<anonymous> (/Users/REDACTED/Workspace/Books/REDACTED/node_modules/gitbook-plugin-index-of-figures/index.js:56:35)
    at initialize.exports.each (/Users/REDACTED/Workspace/Books/REDACTED/node_modules/cheerio/lib/api/traversing.js:300:24)
    at Object.page (/Users/REDACTED/Workspace/Books/REDACTED/node_modules/gitbook-plugin-index-of-figures/index.js:53:30)
    at /Users/REDACTED/.gitbook/versions/3.2.3/lib/output/callHook.js:48:29
    at /Users/REDACTED/.gitbook/versions/3.2.3/lib/utils/promise.js:22:20
    at _fulfilled (/Users/REDACTED/.gitbook/versions/3.2.3/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/REDACTED/.gitbook/versions/3.2.3/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/REDACTED/.gitbook/versions/3.2.3/node_modules/q/q.js:796:13)
    at /Users/REDACTED/.gitbook/versions/3.2.3/node_modules/q/q.js:604:44
    at runSingle (/Users/REDACTED/.gitbook/versions/3.2.3/node_modules/q/q.js:137:13)
```
# Setup

| Environment		| Version		|
|-----------------------|-------------|
| NodeJS			| v9.0.0		|
| Npm				| 5.6.0		|
| macOS High Sierra	| 10.13.2		|
| Gitbook CLI			| 2.3.2		|

## book.json

```
{
	"title": "REDACTED",
	"description": "REDACTED",
	"author": "REDACTED",
	"language": "en",
	"direction": "ltr",
	"plugins": ["katex", "bibtex-citations-and-references", "index-of-figures"],
	"pluginsConfig": {
        "index-of-figures": {
            "path": "./figures.json"
        }
    }
}
```

## figures.json
```
{
    "prefix": "Fig. ",
    "order": "config",
    "figures": {
        "ANN": {
            "path": "/ANN.png",
            "description": "An Artificial Neural Network"
        }
    }
}
```

## file.md
```
{{ "ANN" | fig }}
```

**Comment by geblanco** [comment]
Hi @Maxithi,

First of all, I'm glad to hear this module is useful to someone :).

The error you are seeing is caused because the image itself is not added, this plugin is intended only to reference the figures you use, but it does not insert the figure itself (maybe I should clarify that on the readme??).

To fix it, just add (in this example): `![One hidden layer ANN](/assets/ANN.png)` anywhere in `file.md` and it should work.

Hope this helps and please, if you find any further issue feel free to reopen the issue or open a new one!.

Kind regards :)

**Comment by ghost** [comment]
@m0n0l0c0 That was indeed unclear. Sorry for the invalid report!

**Comment by geblanco** [comment]
Yeah, sorry for the inconvenience, I've updated the readme to reflect that :)
